import type { Metadata } from 'next'
import Providers from '@/lib/Providers'
import { AntdRegistry } from '@ant-design/nextjs-registry'
import './globals.css'


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <AntdRegistry>{children}</AntdRegistry>
        </body>
      </html>
    </Providers>
  )
}
