import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";

import Providers from "@/lib/Providers";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
        <AntdRegistry>
        <html lang="en">
          <body>{children}</body>
        </html>
    </AntdRegistry>
      </Providers>
  );
}
